name: Build Vaultwarden Windows Server
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Vaultwarden Version'
        required: true
        type: string
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone -b ${{ inputs.version }} https://github.com/dani-garcia/vaultwarden.git
          cd vaultwarden
          cargo build --features sqlite --release
          cd target/release
          mkdir vm-image
          cd vm-image
          wget https://raw.githubusercontent.com/jjlin/docker-image-extract/main/docker-image-extract
          chmod +x docker-image-extract
          ./docker-image-extract vaultwarden/server:${{ inputs.version }}-alpine
          cd ..
          mv vm-image/output/web-vault .
          rm -rf vm-image
        env:
          OPENSSL_DIR: 'C:\Program Files\OpenSSL'
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: vaultwarden/target/release
