name: Build Vaultwarden Windows Server
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Vaultwarden Version'
        required: true
        type: string
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone -b ${{ inputs.version }} https://github.com/dani-garcia/vaultwarden.git
          cd vaultwarden
          cargo build --features sqlite --release
          cd target/release
          docker pull vaultwarden/server:${{ inputs.version }}-alpine
          docker create --name vw vaultwarden/server:${{ inputs.version }}-alpine
          docker cp vw:/web-vault .
          docker rm vw
        env:
          OPENSSL_DIR: 'C:\Program Files\OpenSSL'
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: vaultwarden/target/release
