name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone -b 1.33.0 https://github.com/dani-garcia/vaultwarden.git
          cd vaultwarden
          cargo build --features sqlite --release
        env:
          OPENSSL_DIR: "C:\Program Files\OpenSSL"
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: vaultwarden/target/release/vaultwarden.exe
